//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaSYSRetailPlus.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationTypes", Namespace="http://schemas.datacontract.org/2004/07/PharmaSYSRetailPlusService")]
    public enum NotificationTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RefreshProductList = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReFillProductList = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRetailPlusService", CallbackContract=typeof(PharmaSYSRetailPlus.ServiceReference1.IRetailPlusServiceCallback))]
    public interface IRetailPlusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPlusService/RefreshProductList", ReplyAction="http://tempuri.org/IRetailPlusService/RefreshProductListResponse")]
        bool RefreshProductList(string productIDList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPlusService/RefillProductList", ReplyAction="http://tempuri.org/IRetailPlusService/RefillProductListResponse")]
        void RefillProductList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPlusService/ConnectClient", ReplyAction="http://tempuri.org/IRetailPlusService/ConnectClientResponse")]
        void ConnectClient(System.Guid clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPlusService/DisconnectClient", ReplyAction="http://tempuri.org/IRetailPlusService/DisconnectClientResponse")]
        void DisconnectClient(System.Guid clientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IRetailPlusServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRetailPlusService/Notify")]
        void Notify(PharmaSYSRetailPlus.ServiceReference1.NotificationTypes notificationType, string productIdsToRefresh);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IRetailPlusServiceChannel : PharmaSYSRetailPlus.ServiceReference1.IRetailPlusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RetailPlusServiceClient : System.ServiceModel.DuplexClientBase<PharmaSYSRetailPlus.ServiceReference1.IRetailPlusService>, PharmaSYSRetailPlus.ServiceReference1.IRetailPlusService {
        
        public RetailPlusServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RetailPlusServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RetailPlusServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RetailPlusServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RetailPlusServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool RefreshProductList(string productIDList) {
            return base.Channel.RefreshProductList(productIDList);
        }
        
        public void RefillProductList() {
            base.Channel.RefillProductList();
        }
        
        public void ConnectClient(System.Guid clientId) {
            base.Channel.ConnectClient(clientId);
        }
        
        public void DisconnectClient(System.Guid clientId) {
            base.Channel.DisconnectClient(clientId);
        }
    }
}
